### ISSUE TITLE
Peer Review WIKI/README

### ISSUE THREAD

**Issue by RooyyDoe** [StefanGerrits2/functional-programming#5]
# readme
* Goede uitleg van concept geven niet teveel ingaan op de code in je concept.
* Live demo fixen
* Credits fixen
* Uitleggen wat je precies ophaalt met je API call
* fotos van concept voor presentatie misschien? (Donderdag)

# WIKI
* Inhoudsopgave is aardig rommelig (Custom?)
* Concept wat uitgebreider uitleggen. 
* Nergens tegen aan gelopen?
* Goed volgende uitleg dat je mee neemt door de code

**Comment by StefanGerrits2** [comment]
## Readme

* Live demo if gefixt! Het staat op Github pages, link staat in me repo
* Credits zijn ook toegevoegd
* Uitleg API heb ik ook erbij gezet
* Schets van mijn concept staat er nu ook in

## Wiki

* Inhoudsopgave laat ik voor wat het is, dat heeft niet mijn hoogste prioriteit
* Concept heb ik nu iets uitgebreider uitgelegd op de concept pagina
* Dingen waar ik tegenaan liep heb ik vaak op de pagina van het onderwerp staan waar het over ging, hier heb ik geen specifieke pagina voor

### Thanks voor je feedback :)
