### ISSUE TITLE
Peer review Code/Algemeen

### ISSUE THREAD

**Issue by RooyyDoe** [StefanGerrits2/functional-programming#6]
# Code
Code ziet er clean uit en volgens mij doet het wat het zou moeten doen. Weet alleen niet zeker of de cleanData functie functioneel is? Als er een andere query word ingeladen werkt hij dan nog steeds? Zo ja, Niks aan doen!!!

Misschien wat betere benaming voor de functies zou ook fijner zijn om het door te lezen.

# Rubric

Application of subject matter: 5 - 6 naar een 7-8
Understanding: niet te moeilijke code weet wat je aan het doen ben 5 - 6
Quality: 3 - 4 naar een 5 - 6 fix nog even benamingen van je functies en kijk of je misschien dingen kleiner kan maken en of alles functioneel is
Process: Process is goed maar ik weet niet zo goed wat je concept is 5 - 6

# algemeen
Repo leest clean door, maar je moet nog wel even de readme helemaal vullen. werk iets meer aan je concept en schrijf het goed op zodat ik direct kan weten wat je wilt gaan doen etc. Je mist nog **Images**, **Concept**, **Live demo**

**Comment by StefanGerrits2** [comment]
## Code

* Als ik een andere query inlaad, dan werkt deze prima! Er komt dan ook een bubble chart met andere bubbels en benamingen

* Ik vind zelf dat mijn functie benamingen al best specifiek zijn, ik zal er nog wel even naar kijken

## Rubric

* Quality: Naar mijn idee is alles functioneel. Voor betere kwaliteit van mijn code heb ik gebruik gemaakt van ES6 modules, ik importeer dus functies uit andere files zodat mijn main index file clean blijft
* Process: Ik heb dit nu verduidelijkt in mijn readme

## Algemeen

* Readme is aangevuld
* Concept aangevuld
* Image in readme toegevoegd
* Concept beschrijving toegevoegd
* Live demo link gefixt (staat in readme en repo beschrijving)

### Thanks voor je feedback!
